# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `strscan` gem.
# Please instead update this file by running `bin/tapioca gem strscan`.

# source://strscan//lib/strscan/strscan.rb#3
class StringScanner
  # call-seq:
  #   scan_integer(base: 10)
  #
  # If `base` isn't provided or is `10`, then it is equivalent to calling `#scan` with a `[+-]?\d+` pattern,
  # and returns an Integer or nil.
  #
  # If `base` is `16`, then it is equivalent to calling `#scan` with a `[+-]?(0x)?[0-9a-fA-F]+` pattern,
  # and returns an Integer or nil.
  #
  # The scanned string must be encoded with an ASCII compatible encoding, otherwise
  # Encoding::CompatibilityError will be raised.
  #
  # source://strscan//lib/strscan/strscan.rb#15
  def scan_integer(base: T.unsafe(nil)); end
end

StringScanner::Id = T.let(T.unsafe(nil), String)
StringScanner::Version = T.let(T.unsafe(nil), String)
