name: CI

on:
  push:
    branches:
      - main
      - 'ml/**'
  pull_request:
    branches:
      - main

jobs:
  RSpec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - '2.5' # deprecated
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
        include:
          - ruby-version: '3.0'
            coverage: 'true'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: amancevice/setup-code-climate@v0
        name: CodeClimate setup
        if: ${{ matrix.coverage == 'true' }}
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: CodeClimate before-build
        run: cc-test-reporter before-build
        if: ${{ matrix.coverage == 'true' }}
        continue-on-error: true
      - name: Run tests
        env:
          COVERAGE: ${{ matrix.coverage }}
        run: bundle exec rake spec
      - name: CodeClimate after-build
        run: cc-test-reporter after-build
        if: ${{ matrix.coverage == 'true' }}
        continue-on-error: true
  Standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Run Standard
        run: bundle exec rake standard
  Sorbet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
      - name: Check gem RBI files
        run: bin/tapioca gems --verify
      - name: Run Sorbet
        run: bundle exec rake sorbet
